apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: adaptive-inference
resources:
  - ../../base
replicas:
  - name: admin-api
    count: 3
  - name: inference
    count: 3
  - name: retraining-worker
    count: 2
