FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

CMD ["celery", "-A", "worker.retraining_tasks.celery_app", "worker", "--loglevel=INFO"]
